// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8MdZXFh0txzx_iPZ3Sz7_SybIJU2xs00',
    appId: '1:144614727190:web:93d27fa75d351619535f37',
    messagingSenderId: '144614727190',
    projectId: 'talentsync-6675d',
    authDomain: 'talentsync-6675d.firebaseapp.com',
    storageBucket: 'talentsync-6675d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bsx4ynr1JRnY1vEchughhP4MthYbK5Y',
    appId: '1:144614727190:android:d95a16e31a31a2d0535f37',
    messagingSenderId: '144614727190',
    projectId: 'talentsync-6675d',
    storageBucket: 'talentsync-6675d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQXukyKe7TaIQ_TGyTx2R6sPbKgZb57I',
    appId: '1:144614727190:ios:ca004159e36bb621535f37',
    messagingSenderId: '144614727190',
    projectId: 'talentsync-6675d',
    storageBucket: 'talentsync-6675d.firebasestorage.app',
    iosBundleId: 'com.example.talentSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQXukyKe7TaIQ_TGyTx2R6sPbKgZb57I',
    appId: '1:144614727190:ios:ca004159e36bb621535f37',
    messagingSenderId: '144614727190',
    projectId: 'talentsync-6675d',
    storageBucket: 'talentsync-6675d.firebasestorage.app',
    iosBundleId: 'com.example.talentSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8MdZXFh0txzx_iPZ3Sz7_SybIJU2xs00',
    appId: '1:144614727190:web:7edef82605c591bc535f37',
    messagingSenderId: '144614727190',
    projectId: 'talentsync-6675d',
    authDomain: 'talentsync-6675d.firebaseapp.com',
    storageBucket: 'talentsync-6675d.firebasestorage.app',
  );
}
